# Generated by Django 5.2.11 on 2026-02-10 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallScript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('custom_prompt', models.TextField(blank=True, null=True)),
                ('first_message', models.TextField(blank=True, null=True)),
                ('call_goals', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bdc_call_scripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bdc_call_scripts',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bdc_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bdc_contacts',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vapi_call_id', models.TextField(blank=True, null=True, unique=True)),
                ('assistant_id', models.TextField()),
                ('phone_number_id', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('no-answer', 'No Answer'), ('busy', 'Busy'), ('voicemail', 'Voicemail')], default='pending', max_length=32)),
                ('outcome', models.CharField(blank=True, choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('not_interested', 'Not Interested'), ('wrong_number', 'Wrong Number'), ('busy', 'Busy'), ('no_answer', 'No Answer'), ('voicemail', 'Voicemail'), ('language_barrier', 'Language Barrier')], max_length=32, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bdc_calls', to=settings.AUTH_USER_MODEL)),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='calls.callscript')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='calls.contact')),
            ],
            options={
                'db_table': 'bdc_calls',
            },
        ),
    ]
